-----------------------
----- ENVIRONMENT -----
-----------------------

--hl.env("XCURSOR_SIZE", "32")
--hl.env("XCURSOR_THEME", "MacTahoe-dark")
--hl.env("HYPRCURSOR_SIZE", "32")
--hl.env("GDK_BACKEND", "wayland,x11,*")
--hl.env("QT_QPA_PLATFORM", "wayland;xcb")
--hl.env("SDL_VIDEODRIVER", "wayland")
--hl.env("QT_QPA_PLATFORMTHEME", "qtengine")
--hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
